parameters:
    aspose:
        product.class: "Aspose\\Cloud\\Common\\Product"
        app.class: "Aspose\\Cloud\\Common\\AsposeApp"
        utils.class: "Aspose\\Cloud\\Common\\Utils"
        barcodebuilder.class: "Aspose\\Cloud\\Barcode\\BarCodeBuilder"
        barcodereader.class: "Aspose\\Cloud\\Barcode\\BarCodeReader"
        cellscharteditor.class: "Aspose\\Cloud\\Cells\\ChartEditor"
        cellsconverter.class: "Aspose\\Cloud\\Cells\\Converter"
        cellsextractor.class: "Aspose\\Cloud\\Cells\\Extractor"
        cellstexteditor.class: "Aspose\\Cloud\\Cells\\TextEditor"
        cellsworkbook.class: "Aspose\\Cloud\\Cells\\Workbook"
        cellsworksheet.class": "Aspose\\Cloud\\Cells\\Worksheet"
        imagingimage.class: "Aspose\\Cloud\\Imaging\\Image"
        ocrextractor.class: "Aspose\\Cloud\\OCR\\Extractor"
        pdfannotationeditor.class: "Aspose\\Cloud\\Pdf\\AnnotationEditor"
        pdfconverter.class: "Aspose\\Cloud\\Pdf\\Converter"
        pdfdocument.class: "Aspose\\Cloud\\Pdf\\Document"
        pdfextractor.class: "Aspose\\Cloud\\Pdf\\Extractor"
        pdftexteditor.class: "Aspose\\Cloud\\Pdf\\TextEditor"
        slidesconverter.class: "Aspose\\Cloud\\Slides\\Converter"
        slidesdocument.class: "Aspose\\Cloud\\Slides\\Document"
        slidesextractor.class: "Aspose\\Cloud\\Slides\\Extractor"
        storagefolder.class: "Aspose\\Cloud\\Storage\\Folder"
        wordsconverter.class: "Aspose\\Cloud\\Words\\Converter"
        wordsdocument.class: "Aspose\\Cloud\\Words\\Document"
        wordsdocumentbuilder.class: "Aspose\\Cloud\\Words\\DocumentBuilder"
        wordsextractor.class: "Aspose\\Cloud\\Words\\Extractor"
        wordsfield.class: "Aspose\\Cloud\\Words\\Field"
        wordsmailmerge.class: "Aspose\\Cloud\\Words\\MailMerge"
        emailconverter.class: "Aspose\\Cloud\\Email\\Converter"
        emaildocument.class: "Aspose\\Cloud\\Email\\Document"
        tasksconverter.class: "Aspose\\Cloud\\Tasks\\Converter"
        tasksdocument.class: "Aspose\\Cloud\\Tasks\\Document"
        tasksresource.class: "Aspose\\Cloud\\Tasks\\Resource"
        tasksassignment.class: "Aspose\\Cloud\\Tasks\\Assignment"
        taskscalendar.class: "Aspose\\Cloud\\Tasks\\Calendar"

services:
    aspose.product:
        class: "%aspose.product.class%"

    aspose.app:
        class: "%aspose.app.class%"

    aspose.utils:
        class: "%aspose.utils.class%"

    aspose.barcodebuilder:
        class: "%aspose.barcodebuilder.class%"
        arguments:
            - "%filename%"

    aspose.barcodereader:
        class: "%aspose.barcodereader.class%"
        arguments:
            - "%filename%"
            - "%worksheetname%"

    aspose.cellscharteditor:
        class: "%aspose.cellscharteditor.class%"

    aspose.cellsconverter:
        class: "%aspose.cellsconverter.class%"
        arguments:
            - "%filename%"

    aspose.cellsextractor:
        class: "%aspose.cellsextractor.class%"
        arguments:
            - "%filename%"

    aspose.cellstexteditor:
        class: "%aspose.cellstexteditor.class%"
        arguments:
            - "%filename%"

    aspose.cellsworkbook:
        class: "%aspose.cellsworkbook.class%"
        arguments:
             - "%filename%"
             - "%worksheetname%"

    aspose.cellsworksheet:
        class: "%aspose.cellsworksheet.class%"
        arguments:
            - "%filename%"

    aspose.imagingimage:
        class: "%aspose.imagingimage.class%"

    aspose.ocrextractor:
        class: "%aspose.ocrextractor.class%"
        arguments:
            - "%filename%"

    aspose.pdfannotationeditor:
        class: "%aspose.pdfannotationeditor.class%"
        arguments:
            - "%filename%"

    aspose.pdfconverter:
        class: "%aspose.pdfconverter.class%"
        arguments:
            - "%filename%"

    aspose.pdfdocument:
        class: "%aspose.pdfdocument.class%"
        arguments:
            - "%filename%"

    aspose.pdfextractor:
        class: "%aspose.pdfextractor.class%"
        arguments:
            - "%filename%"

    aspose.pdftexteditor:
        class: "%aspose.pdftexteditor.class%"
        arguments:
            - "%filename%"

    aspose.slidesconverter:
        class: "%aspose.slidesconverter.class%"
        arguments:
            - "%filename%"

    aspose.slidesdocument:
        class: "%aspose.slidesdocument.class%"
        arguments:
            - "%filename%"

    aspose.slidesextractor:
        class: "%aspose.slidesextractor.class%"

    aspose.storagefolder:
        class: "%aspose.storagefolder.class%"
        arguments:
            - "%filename%"

    aspose.wordsconverter:
        class: "%aspose.wordsconverter.class%"
        arguments:
            - "%filename%"

    aspose.wordsdocument:
        class: "%aspose.wordsdocument.class%"

    aspose.wordsdocumentbuilder:
        class: "%aspose.wordsdocumentbuilder.class%"
        arguments:
            - "%filename%"

    aspose.wordsextractor:
        class: "%aspose.wordsextractor.class%"

    aspose.wordsfield:
        class: "%aspose.wordsfield.class%"

    aspose.wordsmailmerge:
        class: "%aspose.wordsmailmerge.class%"
        arguments:
            - "%filename%"

    aspose.emailconverter:
        class: "%aspose.emailconverter.class%"
        arguments:
            - "%filename%"

    aspose.emaildocument:
        class: "%aspose.emaildocument.class%"
        arguments:
            - "%filename%"

    aspose.tasksconverter:
        class: "%aspose.tasksconverter.class%"
        arguments:
            - "%filename%"

    aspose.tasksdocument:
        class: "%aspose.tasksdocument.class%"
        arguments:
            - "%filename%"

    aspose.tasksresource:
        class: "%aspose.tasksresource.class%"
        arguments:
            - "%filename%"

    aspose.tasksassignment:
        class: "%aspose.tasksassignment.class%"
        arguments:
            - "%filename%"

    aspose.taskscalendar:
      class: "%aspose.taskscalendar.class%"